### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by BLITZandKILL** [PolarbearDK/Miracle.FileZilla.Api#18]
Has anyone ran across this issue? I get this message about 70% of the time when I am creating a new user, the other 30% it works with no issues.

I feel like I may end up having to make an async method for SetAccountSettings.

`EndOfStreamException: Unable to read beyond the end of the stream.
System.IO.BinaryReader.ReadByte()
Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, byte expected) in BinaryExtensions.cs
Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, byte[] data) in BinaryExtensions.cs
Miracle.FileZilla.Api.FileZillaServerProtocol+<>c__DisplayClass26_0.<Connect>b__0(BinaryReader reader) in FileZillaServerProtocol.cs
Miracle.FileZilla.Api.FileZillaServerProtocol.Receive(Action<BinaryReader> action) in FileZillaServerProtocol.cs
Miracle.FileZilla.Api.FileZillaServerProtocol.Connect(string password) in FileZillaServerProtocol.cs
CustomerPortal.Controllers.AccountController.Register(RegisterViewModel model, string returnUrl) in AccountController.cs`

Stack trace:
`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte expected) in C:\Users\user\Documents\Visual Studio 2017\Projects\CustomerPortalPrototype\Miracle.FileZilla.Api\BinaryExtensions.cs:line 337
   at Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte[] data) in C:\Users\user\Documents\Visual Studio 2017\Projects\CustomerPortalPrototype\Miracle.FileZilla.Api\BinaryExtensions.cs:line 330
   at Miracle.FileZilla.Api.FileZillaServerProtocol.<>c__DisplayClass26_0.<Connect>b__0(BinaryReader reader) in C:\Users\user\Documents\Visual Studio 2017\Projects\CustomerPortalPrototype\Miracle.FileZilla.Api\FileZillaServerProtocol.cs:line 259
   at Miracle.FileZilla.Api.FileZillaServerProtocol.Receive(Action`1 action) in C:\Users\user\Documents\Visual Studio 2017\Projects\CustomerPortalPrototype\Miracle.FileZilla.Api\FileZillaServerProtocol.cs:line 152
   at Miracle.FileZilla.Api.FileZillaServerProtocol.Connect(String password) in C:\Users\user\Documents\Visual Studio 2017\Projects\CustomerPortalPrototype\Miracle.FileZilla.Api\FileZillaServerProtocol.cs:line 286
   at CustomerPortal.Controllers.AccountController.Register(RegisterViewModel model, String returnUrl) in C:\USAGIT\WebApps\CustomerPortal\CustomerPortal\Controllers\AccountController.cs:line 229
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by BLITZandKILL** [comment]
I have figured it out I believe. In FileZilla Server, I had to add the local IP address to the Admin interface allowed IP's setting. Not sure why I had to give it permission to connect to itself, but it seemed to have relieved the above issue.
