### ISSUE TITLE
Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by ramtejsudani** [PolarbearDK/Miracle.FileZilla.Api#20]
Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte expected)
   at Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte[] data)
   at Miracle.FileZilla.Api.FileZillaServerProtocol.<>c__DisplayClass26_0.<Connect>b__0(BinaryReader reader)
   at Miracle.FileZilla.Api.FileZillaServerProtocol.Receive(Action`1 action)
   at Miracle.FileZilla.Api.FileZillaServerProtocol.Connect(String password)
   at HelloWorld.Program.Main(String[] args) in E:\Code\HelloWorld\Program.cs:line 22

**Comment by ramtejsudani** [comment]
Used invalid port and password was not set
